# Generated by Django 5.0.2 on 2026-08-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_processedpaymentevent_developer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorybatch',
            options={'ordering': [models.OrderBy(models.F('expiration_date'), nulls_last=True), 'id'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
    ]
