# Generated by Django 5.0.2 on 2026-08-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_inventorybatch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=500, unique=True)),
                ('last_crawled_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crawled_url',
                'indexes': [models.Index(fields=['last_crawled_at'], name='crawled_url_last_cr_91c8df_idx')],
            },
        ),
    ]
