# Generated by Django 5.0.2 on 2026-08-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_crawledurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
