# Generated by Django 6.1 on 2026-08-15 10:38

from django.db import migrations


def travar_plano_free(apps, schema_editor):
    """
    Modelo somente-leitura pós-teste, igual ao que 1Password, Bluebeam e
    Sage usam quando uma assinatura vence — mantém todo o histórico
    visível (Meu Estoque, Dashboard, Extrato), mas trava as ações que
    fariam a consultora seguir usando o sistema de graça pra sempre:
    cadastrar produto novo e registrar venda.

    O plano 'free' aqui representa especificamente "teste acabou, sem
    assinar" — não é mais um nível de uso permanente e utilizável.

    get_or_create em vez de um update() puro: não dá pra assumir que a
    linha 'free' já existe em todo ambiente (dev, produção, banco de
    teste) — se não existir, cria já com os valores certos, em vez de um
    update() silenciosamente não fazer nada.
    """
    PlanConfig = apps.get_model('inventory', 'PlanConfig')
    PlanConfig.objects.update_or_create(
        plan_type='free',
        defaults=dict(
            display_name='Free',
            max_products=0,
            can_use_scanner=False,
            can_use_storefront=False,
            can_use_alerts=False,
            can_use_ai_assistant=False,
            can_use_analytics=False,
            can_export_data=False,
            can_use_api=False,
        ),
    )


def reverter(apps, schema_editor):
    """Sem reversão automática — os valores anteriores não foram registrados."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_store_onboarding_completed'),
    ]

    operations = [
        migrations.RunPython(travar_plano_free, reverter),
    ]
