# Generated by Django 6.1 on 2026-08-16 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_esconder_plano_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('label', models.CharField(blank=True, help_text="Anotação livre pra identificar quem é — ex: 'Líder Maria, grupo de 40'", max_length=200)),
                ('bonus_trial_days', models.PositiveIntegerField(default=30, help_text='Dias de teste que quem USA o código ganha (em vez do padrão).')),
                ('referrer_bonus_days', models.PositiveIntegerField(default=7, help_text='Dias extras que quem INDICOU ganha quando o código é usado.')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Limite de usos. Vazio = sem limite.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referrer_store', models.ForeignKey(blank=True, help_text='Quem criou/está indicando — recebe o bônus de dias quando o código é usado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_codes_owned', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Código de Indicação',
                'verbose_name_plural': 'Códigos de Indicação',
                'db_table': 'referral_code',
            },
        ),
        migrations.CreateModel(
            name='ReferralUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='inventory.referralcode')),
                ('referred_store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_use', to='inventory.store')),
            ],
            options={
                'db_table': 'referral_use',
            },
        ),
    ]
