# Generated by Django 6.1 on 2026-08-16 11:20

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_referralcode_referraluse'),
    ]

    operations = [
        # ⚠️ NOVO: o índice GIN com gin_trgm_ops abaixo depende da extensão
        # pg_trgm estar habilitada no Postgres — sem esta operação vindo
        # primeiro, a migration falha ao aplicar num banco de verdade
        # (Django não adiciona isso sozinho no makemigrations).
        TrigramExtension(),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
