# Generated by Django 6.1 on 2026-08-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_product_product_name_trgm_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(help_text="Ex: 'checkin', 'upgrade_pago'", max_length=50)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_enviados', to='inventory.store')),
            ],
            options={
                'db_table': 'email_enviado',
                'unique_together': {('store', 'template')},
            },
        ),
    ]
