# Generated by Django 6.1 on 2026-08-17 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_emailenviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappContatoMarcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=50)),
                ('marcado_em', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_marcados', to='inventory.store')),
            ],
            options={
                'db_table': 'whatsapp_contato_marcado',
                'unique_together': {('store', 'template')},
            },
        ),
    ]
