# Generated by Django 6.1 on 2026-08-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_whatsappcontatomarcado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailenviado',
            options={'ordering': ['-enviado_em']},
        ),
        migrations.AlterModelOptions(
            name='whatsappcontatomarcado',
            options={'ordering': ['-marcado_em']},
        ),
        migrations.AlterUniqueTogether(
            name='emailenviado',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappcontatomarcado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emailenviado',
            name='assunto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailenviado',
            name='corpo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='whatsappcontatomarcado',
            name='texto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailenviado',
            name='template',
            field=models.CharField(blank=True, help_text='Modelo usado como ponto de partida, se algum.', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappcontatomarcado',
            name='template',
            field=models.CharField(blank=True, help_text='Modelo usado como ponto de partida, se algum.', max_length=50),
        ),
    ]
