# Generated by Django 6.1 on 2026-08-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_emailenviado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='email_suporte',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='whatsapp_suporte',
            field=models.CharField(blank=True, help_text='Só números, com DDI e DDD — ex: 5547999998888', max_length=20),
        ),
    ]
