# Generated by Django 6.1 on 2026-08-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_systemconfig_email_suporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='video_apresentacao_url',
            field=models.URLField(blank=True),
        ),
    ]
