"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""
import os
import sys
import json
import logging
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from cryptography.fernet import Fernet
from django.core.exceptions import ImproperlyConfigured

# ==========================================
# 🔧 CONFIGURAÇÕES BASE
# ==========================================

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))

# ✅ CRÍTICO: Ler DEBUG primeiro (afeta outras configurações)
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# ✅ CRÍTICO PARA RENDER: Ler PORT da variável de ambiente
PORT = os.getenv("PORT", "8000")

# ✅ CRÍTICO: ALLOWED_HOSTS dinâmico para Render/Vercel
ALLOWED_HOSTS = [
    'localhost', '127.0.0.1', '0.0.0.0',
    'gestao-estoque-one.vercel.app',
    'gestao-estoque-k5vy.onrender.com',
    'dev-brih.onrender.com',
    '.vercel.app', 
    '.onrender.com',  # ✅ Permite todos os subdomínios do Render
    '.herokuapp.com',
]

# ✅ Adicionar hostname externo do Render dinamicamente
render_hostname = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if render_hostname:
    ALLOWED_HOSTS.append(render_hostname)

# ✅ Em produção, forçar DEBUG=False se não estiver explícito
if not os.getenv("RENDER") and not DEBUG:
    DEBUG = False

# ==========================================
# 🔐 SECURITY SETTINGS (PRODUÇÃO)
# ==========================================

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY and DEBUG:
    SECRET_KEY = "django-insecure-dev-key-change-in-production"
elif not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY must be set in production")

# ✅ Configurações de segurança para proxy (Render/Vercel)
if os.getenv("RENDER") or os.getenv("VERCEL"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    
    if not DEBUG:
        SECURE_SSL_REDIRECT = True
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_HSTS_SECONDS = 3600
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = False

# ✅ COOP para permitir popups do Firebase Auth
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# ==========================================
# 🔐 CORS CONFIGURATION
# ==========================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", "http://localhost:5173",
    "http://127.0.0.1:3000", "http://127.0.0.1:5173",
    "https://minhaamora.com.br", "https://www.minhaamora.com.br",
    "https://api.minhaamora.com.br",
    "https://gestao-estoque-one.vercel.app",
    "https://gestao-estoque-dev-one.vercel.app",
    "https://gestao-estoque-k5vy.onrender.com",
    "https://dev-brih.onrender.com",
    "https://*.firebaseapp.com", "https://*.googleapis.com",
    "https://*.google.com", "https://*.gstatic.com",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
    r"^https://.*\.onrender\.com$",
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept", "accept-encoding", "authorization", "content-type",
    "dnt", "origin", "user-agent", "x-csrftoken", "x-requested-with",
    "x-firebase-locale", "x-firebase-gmpid", "x-client-data",
    "x-goog-authuser", "x-firebase-app-check",
]
CORS_ALLOW_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT"]

CSRF_TRUSTED_ORIGINS = [
    "https://minhaamora.com.br", "https://www.minhaamora.com.br",
    "https://gestao-estoque-one.vercel.app",
    "https://gestao-estoque-dev-one.vercel.app",
    "https://gestao-estoque-k5vy.onrender.com",
    "https://dev-brih.onrender.com",
]

# ==========================================
# 📦 INSTALLED APPS & MIDDLEWARE
# ==========================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_spectacular',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'inventory',
    'ai',
    'apps.payments',
]

# ✅ ORDEM CRÍTICA DO MIDDLEWARE
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'inventory.middleware.ApiKeyMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'
WSGI_APPLICATION = 'core.wsgi.application'

# ==========================================
# 🗄️ DATABASE CONFIGURATION
# ==========================================

DB_NAME = os.getenv("DB_NAME", "natura_inventory")
DB_USER = os.getenv("DB_USER", "natura_admin")
DB_PASSWORD = os.getenv("DB_PASSWORD", "")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")

database_url = os.getenv("DATABASE_URL")
if database_url:
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.parse(
            database_url,
            conn_max_age=600,
            conn_health_checks=True,
            disable_server_side_cursors=True,
        )
    }
    print(f"✅ PostgreSQL configurado via DATABASE_URL", file=sys.stderr)
elif all([DB_NAME, DB_USER, DB_PASSWORD]):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": DB_PORT,
            "CONN_MAX_AGE": 600,
            "CONN_HEALTH_CHECKS": True,
            # ✅ Otimizações para Render
            "OPTIONS": {
                "connect_timeout": 10,  # Timeout de conexão mais curto
            }
        }
    }
    print(f"✅ PostgreSQL local configurado: {DB_NAME}", file=sys.stderr)
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("⚠️ SQLite configurado (apenas para dev)", file=sys.stderr)

# ==========================================
# 💾 CACHING CONFIGURATION (NOVO - CRÍTICO PARA PERFORMANCE)
# ==========================================

# ✅ Cache em memória para desenvolvimento/Render free tier
# Para produção com Redis, use a configuração comentada abaixo
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
        "TIMEOUT": 300,  # 5 minutos
        "OPTIONS": {
            "MAX_ENTRIES": 1000,  # Limitar entradas para evitar uso excessivo de memória
        }
    }
}

# ✅ Para produção com Redis (descomente quando adicionar Redis no Render):
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             "SOCKET_CONNECT_TIMEOUT": 5,
#             "SOCKET_TIMEOUT": 5,
#             "CONNECTION_POOL_KWARGS": {"max_connections": 50},
#             "RETRY_ON_TIMEOUT": True,
#         },
#         "TIMEOUT": 300,
#     }
# }

# ✅ Cache de templates para performance
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # ✅ Cache de templates em produção
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ])
            ] if not DEBUG else [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

# ==========================================
# 🔐 AUTH & JWT
# ==========================================

AUTH_USER_MODEL = "inventory.CustomUser"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ==========================================
# 🚀 DJANGO REST FRAMEWORK - OTIMIZAÇÕES
# ==========================================

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    # ✅ Otimizações de performance
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,  # Limitar resultados por página
    'MAX_PAGINATE_BY': 100,
    # ✅ Throttling para prevenir abuso (ajustar conforme plano)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',    # Anônimos: 100 req/hora
        'user': '1000/hour',   # Autenticados: 1000 req/hora
    },
}

# ==========================================
# 📚 SWAGGER / OPENAPI
# ==========================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'Minha Amora API',
    'DESCRIPTION': 'API comercial para acesso ao banco de dados de produtos de beleza.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Catalog', 'description': 'Catálogo global de produtos'},
        {'name': 'Lookup', 'description': 'Busca por código de barras'},
        {'name': 'Storefront', 'description': 'Vitrines públicas'},
        {'name': 'Analytics', 'description': 'Analytics agregados (Enterprise)'},
        {'name': 'Webhooks', 'description': 'Notificações em tempo real'},
    ],
    'SECURITY': [{'ApiKeyAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'ApiKeyAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'Authorization',
                'description': 'API Key no formato: Bearer pk_live_••••',
            }
        }
    },
}

# ==========================================
# 🔥 FIREBASE ADMIN - Inicialização robusta
# ==========================================

try:
    import firebase_admin
    from firebase_admin import credentials
    
    firebase_json_str = os.environ.get("FIREBASE_CREDENTIALS")
    
    if firebase_json_str:
        try:
            firebase_json_str = firebase_json_str.replace('\\n', '\n')
            firebase_creds_dict = json.loads(firebase_json_str)
            
            required_fields = ['type', 'project_id', 'private_key', 'client_email']
            missing = [f for f in required_fields if f not in firebase_creds_dict]
            if missing:
                raise ValueError(f"Firebase JSON missing fields: {missing}")
            
            cred = credentials.Certificate(firebase_creds_dict)
            
            if not firebase_admin._apps:
                firebase_admin.initialize_app(cred, {
                    'projectId': firebase_creds_dict.get('project_id'),
                })
                print("✅ Firebase Admin inicializado com sucesso.", file=sys.stderr)
            else:
                print(f"ℹ️ Firebase Admin já inicializado ({len(firebase_admin._apps)} app(s)).", file=sys.stderr)
                
        except json.JSONDecodeError as e:
            print(f"❌ Firebase JSON inválido: {e}", file=sys.stderr)
            if DEBUG:
                print(f"🔍 Raw credentials length: {len(firebase_json_str)}", file=sys.stderr)
        except ValueError as e:
            print(f"❌ Firebase config error: {e}", file=sys.stderr)
        except Exception as e:
            print(f"❌ Falha ao inicializar Firebase Admin: {type(e).__name__}: {e}", file=sys.stderr)
            if DEBUG:
                import traceback
                traceback.print_exc(file=sys.stderr)
    else:
        print("⚠️ Variável FIREBASE_CREDENTIALS não encontrada.", file=sys.stderr)
        
except ImportError:
    print("⚠️ Firebase Admin SDK não instalado.", file=sys.stderr)

# ==========================================
# 💳 ASAAS CONFIGURATION
# ==========================================

ASAAS_API_KEY = os.environ.get('ASAAS_API_KEY', '')
ASAAS_ENVIRONMENT = os.environ.get('ASAAS_ENVIRONMENT', 'sandbox')
ASAAS_WEBHOOK_TOKEN = os.environ.get('ASAAS_WEBHOOK_TOKEN', '')

ASAAS_BASE_URLS = {
    'sandbox': 'https://sandbox.asaas.com/api/v3',
    'production': 'https://api.asaas.com/v3',
}
ASAAS_BASE_URL = ASAAS_BASE_URLS.get(ASAAS_ENVIRONMENT, ASAAS_BASE_URLS['sandbox'])

# ==========================================
# 🌐 I18N & STATIC
# ==========================================

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ==========================================
# 📝 LOGGING CONFIGURATION
# ==========================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {message}',
            'style': '{',
        },
        'safe': {
            'format': '[%(asctime)s] %(levelname)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'stream': sys.stderr,
        },
        'console_safe': {
            'class': 'logging.StreamHandler',
            'formatter': 'safe',
            'stream': sys.stderr,
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'inventory': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

if not DEBUG:
    LOGGING['root']['handlers'] = ['console_safe']

# ==========================================
# 🔐 LGPD CONFIGURAÇÕES
# ==========================================

LGPD_IP_SALT = os.environ.get("LGPD_IP_SALT", "mude-para-string-aleatoria-segura-min-32chars")
LGPD_CONSENT_RETENTION_DAYS = 730  # 2 anos
LGPD_ESSENTIAL_PURPOSES = ["essential", "authentication", "legal_compliance", "service_delivery"]
LGPD_CONSENT_VERSION = "v1.0_2026-05"

# ==========================================
# 🚀 STARTUP LOGS
# ==========================================

print(f"✅ Settings carregado com sucesso!", file=sys.stderr)
print(f"📊 DEBUG: {DEBUG}", file=sys.stderr)
print(f"🔧 PORT: {PORT}", file=sys.stderr)
print(f"🗄️ Database: {DATABASES['default']['ENGINE']}", file=sys.stderr)
print(f"💾 Cache: {CACHES['default']['BACKEND']}", file=sys.stderr)
print(f"🌐 ALLOWED_HOSTS: {ALLOWED_HOSTS[:3]}... ({len(ALLOWED_HOSTS)} total)", file=sys.stderr)

if os.getenv("RENDER"):
    print(f"🎯 Running on Render - Hostname: {render_hostname or 'N/A'}", file=sys.stderr)