# Generated by Django 5.0.2 on 2026-08-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('video', 'Vídeo'), ('faq', 'Pergunta frequente'), ('guia', 'Guia'), ('novidade', 'Novidade')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('corpo', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('visivel', 'Visível')], default='rascunho', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordem', '-created_at'],
                'indexes': [models.Index(fields=['status', 'tipo'], name='ai_helpcont_status_4dd776_idx'), models.Index(fields=['status', 'categoria'], name='ai_helpcont_status_90a24a_idx')],
            },
        ),
    ]
