# Generated by Django 5.0.2 on 2026-08-06 03:08
#
# ⚠️ Migração de DADOS (não altera schema) — copia cada TutorialVideo
# existente pra um HelpContent novo, com tipo='video' e status='visivel'
# (todo vídeo hoje é considerado publicado, já que a tela atual não tem
# rascunho). TutorialVideo NÃO é apagado nem alterado — só lido. Reversível:
# ao migrar pra trás, apaga os HelpContent que foram criados por esta
# migração (tipo='video'), sem tocar nos TutorialVideo originais.
from django.db import migrations


def copiar_videos(apps, schema_editor):
    TutorialVideo = apps.get_model('ai', 'TutorialVideo')
    HelpContent = apps.get_model('ai', 'HelpContent')

    for video in TutorialVideo.objects.all():
        HelpContent.objects.create(
            tipo='video',
            titulo=video.title,
            corpo=video.description or '',
            video_url=video.video_url,
            categoria=video.category or '',
            status='visivel',
            ordem=video.sort_order,
        )


def reverter_copia(apps, schema_editor):
    HelpContent = apps.get_model('ai', 'HelpContent')
    HelpContent.objects.filter(tipo='video').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_helpcontent'),
    ]

    operations = [
        migrations.RunPython(copiar_videos, reverter_copia),
    ]
