# Generated by Django 5.0.2 on 2026-08-06 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_copiar_videos_para_help_content'),
        ('inventory', '0020_alter_inventorybatch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_hits', to='ai.helpcontent')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
